// src/config/site.ts
//
// The single source of truth for everything client-specific.
// Every component and page reads from this file — never hard-code a
// client's name, phone, services, or colors directly into a component.
// To build a new client site: copy this file, fill in their details,
// and toggle the features they purchased. Nothing else should need to change.
//
// brandColor drives the entire visual palette: src/utils/palette.ts derives
// a full tonal scale (50-950) from this single hex value at build time, so
// changing one value here re-themes the whole site (see Base.astro).
//
// images.* and each service's `image` field point at static files under
// public/images/ — these are manually uploaded photos (client-provided or
// licensed stock), not generated by any build step. There is no AI image
// generation in this pipeline. Drop a file into public/images/, then set
// the matching field below to its path, e.g. "/images/hero.jpg". Leave a
// field unset (or omit `image`) and the relevant component falls back to
// a labeled placeholder box automatically.
//
// This file currently contains a realistic DEMO business (a plumbing
// company) so the template is fully demo-ready out of the box — replace
// every value below with the real client's details when starting a build.

export interface Service {
  name: string;
  slug: string;             // used in the URL: /services/[slug]
  shortDescription: string; // one sentence, shown on the services grid
  description: string;      // longer paragraph, shown on the service's own page
  image?: string;           // path under /images/ — manually uploaded, leave unset to show placeholder
}

export interface SiteImages {
  hero?: string;   // homepage hero photo, e.g. "/images/hero.jpg" — manually uploaded
  about?: string;  // about-page photo — same convention as hero
}

// ─── Visual theme knobs ────────────────────────────────────────────────────────
// All fields are optional — safe to omit entirely. Defaults are applied in each
// component. Change these to differentiate a client's site without touching any
// component files.
export interface SiteTheme {
  // Header background: "white" = white + border (default), "brand" = brand-700 bg + white text
  headerStyle?: "white" | "brand";

  // Hero layout: "split" = text-left / image-right (default), "centered" = centered text only
  heroLayout?: "split" | "centered";

  // Show a subtle dot-grid pattern behind the hero section (default: true)
  heroPattern?: boolean;

  // Footer background: "dark" = slate-900 (default), "brand" = brand-900
  footerStyle?: "dark" | "brand";

  // Whether to show the TrustBar strip (years, reviews, licensed, areas) below Hero (default: true)
  showTrustBar?: boolean;

  // Card/button corner radius: "sm" | "md" (default) | "lg" | "full"
  roundness?: "sm" | "md" | "lg" | "full";
}

export interface SiteConfig {
  business: string;
  tagline: string;
  // Short eyebrow label shown above the tagline in the Hero section.
  // e.g. "Frisco's Most-Trusted Plumber" — keep under 60 chars.
  heroEyebrow?: string;
  phone: string;
  phoneDisplay: string;  // human-friendly formatting, e.g. "(972) 555-0148"
  email: string;
  emailDomain: string;   // domain used in the "from" address for Resend, e.g. "smithplumbing.com"
  address: string;       // keep this EXACT format identical everywhere (NAP consistency, SEO)
  city: string;
  state: string;
  zip: string;
  serviceAreas: string[];
  services: Service[];
  images: SiteImages;
  brandColor: string;    // single hex value — drives the entire color palette via palette.ts
  yearsInBusiness: number;
  googleReviewLink: string;
  googleRating: number;
  googleReviewCount: number;
  businessStory: string;

  // Optional tagline override shown in the footer. Defaults to site.tagline.
  footerTagline?: string;

  // Optional visual theme overrides. All fields default to the values noted in SiteTheme.
  theme?: SiteTheme;

  features: {
    reviewsWidget: boolean;  // upsell: live embedded Google reviews widget
    booking: boolean;        // upsell: Cal.com appointment booking
    smsForwarding: boolean;  // upsell: forward inquiries to owner's cell via Twilio
  };

  calLink: string;    // Cal.com booking link — fill in only when features.booking is true
  ownerCell: string;  // owner's cell in E.164 format (e.g. "+19725550148") — fill in only when features.smsForwarding is true
}

export const site: SiteConfig = {
  business: "Smith Plumbing Co.",
  tagline: "Fast, honest plumbing for Frisco and the North Dallas area",
  heroEyebrow: "Serving Frisco & North Dallas Since 2012",
  phone: "+19725550148",
  phoneDisplay: "(972) 555-0148",
  email: "smith@smithplumbing.com",
  emailDomain: "smithplumbing.com",
  address: "123 Main St, Frisco, TX 75034",
  city: "Frisco",
  state: "TX",
  zip: "75034",
  serviceAreas: ["Frisco", "Plano", "McKinney", "Allen", "The Colony", "Prosper"],
  businessStory: "Since 2012, Smith Plumbing Co. has been serving the Frisco and North Dallas area with fast, honest plumbing services. Our team is committed to providing quality work and exceptional customer service, ensuring that every job is done right the first time.",

  services: [
    {
      name: "Emergency Plumbing",
      slug: "emergency-plumbing",
      shortDescription: "Burst pipe or major leak? We answer the phone and show up fast, day or night.",
      description:
        "Plumbing emergencies don't wait for business hours, and neither do we. Whether it's a burst pipe, a sudden leak, or a backed-up line, our team responds quickly to stop the damage and get your home or business back to normal. We carry the parts and tools to fix most emergencies on the first visit.",
    },
    {
      name: "Water Heaters",
      slug: "water-heaters",
      shortDescription: "Repair, replacement, and installation for tank and tankless water heaters.",
      description:
        "From a pilot light that won't stay lit to a full replacement, we work on both traditional tank and modern tankless water heaters. We'll give you a straight answer on whether a repair makes sense or if it's time to replace, and we carry units in stock for same-week installs.",
    },
    {
      name: "Drain Cleaning",
      slug: "drain-cleaning",
      shortDescription: "Slow or clogged drains cleared the right way — no harsh chemicals needed.",
      description:
        "Slow drains are usually a warning sign, not just an inconvenience. We use professional-grade equipment to clear clogs at the source rather than masking the problem, and we'll let you know if there's a larger issue worth keeping an eye on.",
    },
  ],

  images: {
    // Demo starts with no images — drop files into public/images/ and set these:
    hero: "/images/hero.jpg",
    //   about: "/images/about.jpg",
  },

  brandColor: "#1a6fd4",   // light blue — change this single value to re-theme the entire site
  yearsInBusiness: 12,
  googleReviewLink: "https://g.page/r/REPLACE_ME/review",
  googleRating: 4.9,
  googleReviewCount: 87,

  // Theme: all fields below are optional — remove any line to use its default
  theme: {
    headerStyle: "white",
    heroLayout: "split",
    heroPattern: true,
    footerStyle: "dark",
    showTrustBar: true,
    roundness: "md",
  },

  features: {
    reviewsWidget: false,
    booking: false,
    smsForwarding: false,
  },

  calLink: "",
  ownerCell: "",
};
